// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Columns_Trademark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Columns_Trademark));
        
        string IMigrationMetadata.Id
        {
            get { return "201609231618277_Add_Columns_Trademark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Z227bOBB9X6D/IOg5tWIHLXYDuUVqJwtj6ziokr7T0tghSpFaksrG37YP+0n7CzvU/WZHcpxFESBwSM6ZmTPkXJx///7H/fwcMusJpKKCT+3x6Ny2gPsioHw7tWO9ef+r/fnTu1/c6yB8tr7n5y7MOZTkamo/ah1dOo7yHyEkahRSXwolNnrki9AhgXAm5+e/OeOxAwhhI5Zlud9irmkIyR/450xwHyIdE7YUATCVreOOl6BatyQEFREfpra3mK1GC76RRGkZ+zqWMJoTTUZLQvloSbeSaLRR2dYVowTt84BtbItwLnSyc/mgwNNS8K0X4QJh97sI8NyGMAWZV5fl8b4Onk+Mg04pmEP5sdIiHAg4vsgYc5riR/FuF4wip9fIvd4ZrxNep/a9JAFiyB+21dR2OWPSnMx4n+OeYdn8KqRU+fHMah47Ky4N3i3zc2bNYmaiNuUQa0nYmXUXrxn1/4DdvfgBfMpjxqoGo8m4V1vApTspIpB69w02mRuLwLacupzTFCzEKjKpfwuuLya2dYvKyZpBcR8qXHhaSPgdOOAVg+COaA2SGwxIGG1pb+gyv3NteAHxhdnWkjx/Bb7Vj1P7Az6pG/oMQb6QGfDAKb5HlMHrDh0GHlY6Q9EDSj++hU7vUUj9grfj837uHta0+guDcUhLT1IPa7nyNX0qnPkiBAPCh0dCQnKNMFkVWObzPQ2PCKsBE3IRXQWBBKUOcDB5m3uVGoC59BD/b6Pbw/cYq9fG4yEKkP3uaPSRPCX5vfSdhuuqKtcpa0G7QmBV1pjBQWZmzNcmoZtVeNYdpQLty6qFypTVvUpRPdDNsoMElnakBXtUqUldFhe2la2Ck/YKeU/h7Gkq3CWJIuSu0mRkK5aXdhiz997wIhumGI6vOmptYW2hCZ8O2UJjN83WN1QqbTqaNTHhmwVh61g9EntYznW1yG5W0pL7XMR8zp5az26rEq8GfMnvDbocYqlMvIfCzmr/0ZJNWkDCiOyo2zPB4pDvq/2HpNPaVJVPV/ojpGW1ipCu9EeoFMkqTGW5P1ZWBqs42VJ/jLzIVUHytQG81IpcjZ/azkDEWqVrodZ2ByOnabUDNN0YENGsLNXCma31R6mWpSpSdX0o2j722ruDkdvs1TbaeK7TSAfNdOS08lGjp29muEPloXmk0F6UiUY5cLPU/PIg2srV6RHbQqKeaGDytLdTGsI0YXp/shmj6G95YEk43YDS6diDBXw8aUytP88E6SgVsL5j5P8+vFFD64vj2cAGsTrB8Cci/UciWxPbK8axTsyPr5+2OnGTeatEHjxcdYN+GAxan6XWVJ9kjjIZR59yjup0d3JEvNtj0qmg61PQMUy2J6AuHgdMKMfQeOQAdBTysHmn3Yz3nGcOjzNpmUCu1wKdSU19/bTTLluuU/2W1Z2DotsSwnznysE3D6kEzc9gwy/yEKB/VYvyI40ILUETjBG5kppuiK9x28d7kMyo3wmL8ch1uIZgwVexjmJ9pRSEa1b7zsx1DutPRrq6ze4qSsaPU7iAZlJzzVb8S0xZUNh9035K+yDMjckKEFqFMzrCbXcF0q3gPYEy+uYQATfl6x7CiCGYWnGPmPQ53DZ8PF9hS/xd3n3sB3k5EHXa3TklOAiGKsMo5c1/Dhzzr4NP/wEfA+LbbBgAAA=="; }
        }
    }
}
