// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Columns_Size_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Columns_Size_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "201609271919431_Update_Columns_Size_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Z227jNhB9L9B/EPTUAlnLdoCiDexdZO2kMLpOglWy77Q0doilSJWkAru/1od+Un+hQ91vtiXHWRRFESCweTkzczgczoz//vOvyYdtwKwXkIoKPrVHg6FtAfeET/lmakd6/e5n+8P777+b3PjB1vqSrbs063AnV1P7WevwynGU9wwBUYOAelIosdYDTwQO8YUzHg5/cUYjBxDCRizLmnyOuKYBxF/w60xwD0IdEbYUPjCVjuOMG6NadyQAFRIPpra7mN0PFnwtidIy8nQkYTAnmgyWhPLBkm4k0aijsq1rRgnq5wJb2xbhXOh45upJgaul4Bs3xAHCHnch4Lo1YQpSq66K5V0NHI6NgU6xMYPyIqVF0BNwdJky5tS3n8S7nTOKnN4g93pnrI55ndqPkviIIb/aVl3a1YxJszLlfY5zhmXzL9+lio8XVn3ZRe406Fvm78KaRcyc2pRDpCVhF9ZDtGLU+w12j+Ir8CmPGCsrjCrjXGUAhx6kCEHq3WdYp2YsfNtyqvuc+sZ8W2lPYt+C68uxbd2hcLJikPtDiQtXCwm/Agd0MfAfiNYgucGAmNGG9Jos8z+Thg6IN8y2lmT7CfhGP09t/Ghbt3QLfjaSavDEKV5I3IT+DseEzHDlASE/dRJx3OaZCMIIB46qIyHGwRuaq2U+P1LDRYPsDmBCLsJr35eg1AE7x8NOhp6mAAYQ+c1lu3ggUW7yRyEYEN4b5Sn0kf320+iy85zkd5J3Hq7LoiZOEQAPhsXrF0Jjbj/Bhni75Gb1CJAt+1Xb4P9B8/R4NnqTu7bwjcBcLCYQg+K4kqmeiBW8twkZ+/06CkpeXTdkoW4Z2RT5Tw8HN8iQpls1gs7n08iBD5LtkLKyz1XZXkKwAtlMZ74QFuHIsHE8lQ0zwYTMF48OL3bpH5CvHR9fm7Ccrr9sHllyOM1AhDmxRtpyrPnKsGhGYatbjgkDZXpSKnWXqmIJqgu6zhJG8sJxUm8vUegchmkLci2ArbG0zXtzs4sawEmKgKxYcPZUC5MlCUP0klL1kI5YblI6zN65/bPnIMFwPNWSROfa5pIw2pEN1GaTMHZLpdKmVFkRc9FmftBYVj3kPcxnshrnWI/2xSlkW8zn1DU7llElV6jBF/zeoskBhvPYesj1LN/Ext64tiOMyJa3Be9jFPB979Oh3UmKXd6fjHRHSDyzjND01SMIlZS3glSZ6YlYyXsbqJXZ3shJktUCmkx0x8uS1DJUNtYdpZyklpHK433R9rHXnO2N3GSvMtHEmzi1i1O/uE7j5tYytHos6BQpWkP1m8SMtmjfP3p0QnmbOPL6KJClkFUdkrHuKE2MfQhv6lONx7m+JJeeP9K1x3iSPozH+3uNlzJZYltIzQv1zSvp7pSGIHE993c2YxTtLRYsCadrUDpJIjG3Ho1rzcB/T2POUcpnXbtz37y8o4bWowVcz1Ko3AbjL0R6z0T+EJDtj2Wkvq2uDKje7DravuopsqWdZUK9Pmc7q9UWUyG+vlt1LuhqM2pF9RkaUW089mgUnULjiX2ok5Bf1Xb6b9z88oVto3DU3xGrnZpY61d0Zk66HYcPtl7GNwvBjmX64So9eSTxEq0EGpPo+qoivmsN3yb4nMV+M2+YOOVfDydzUHRTQJjfEjl4JkgXoNkazF1FdvxofVmjbEnNO5agCd5/ci01XRNP47SHMSbu36U9nZtgBf6C30can5RrpSBYsUpbc+Iclh93NKo6T+7DOJM+hwmoJjUh7J5/jCjzc71vW1x5D4Q5wTQOoFauNvFgs8uR7gTvCJTSN4cQuIkijxCEDMHUPXfJC5yiGwbmxM2y9G8/yPGDqNI+mVOCNU2gUoxiv/lF3DE/ib//B9UST6REHwAA"; }
        }
    }
}
