// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Table_Color : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Table_Color));
        
        string IMigrationMetadata.Id
        {
            get { return "201609222025160_Add_Table_Color"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1azW7jNhC+F+g7CDq1QNaKs5c2kHeRtZMi6DoJVsneaWnsEEtRKkkF9rP10EfqK3SoX+rHjhQ7abcwFsjaJOfjzHD4cWaSv//8y/24Dpn1BELSiE/s8ejUtoD7UUD5amInavnuF/vjhx9/cC+DcG19Lda91+tQksuJ/ahUfO440n+EkMhRSH0RyWipRn4UOiSInLPT01+d8dgBhLARy7LcLwlXNIT0C36dRtyHWCWEzaMAmMzHccZLUa0bEoKMiQ8T27ue3o6u+VIQqUTiq0TAaEYUGc0J5aM5XQmiUEdpWxeMEtTPA7a0LcJ5pNKZ8wcJnhIRX3kxDhB2v4kB1y0Jk5BbdV4t72vg6Zk20KkECyg/kSoKBwKO3+cec5riL/K7XXoUfXqJvlcbbXXq14l9L0iAGOKbbTV3O58yoVfmfp/hnPay/lFKyerjidVcdlIGDcaW/ndiTROmT23CIVGCsBPrLlkw6v8Om/voG/AJTxgzFUaVca42gEN3IopBqM0XWOZmXAe25dTlnKZgKWbIZPZdc/X+zLZucHOyYFDGg+ELT0UCfgMOGGIQ3BGlQHCNAalHW7s39tI/i90wAPGG2dacrD8DX6nHiY0fbeuKriEoRnINHjjFC4lCGO/w3CYe6prIYptPUcSA8A6zdqNMBWgT8V6VGuvP91RbMBDrIQ62Y/VS4zq+CAIBUu7w3tlpL+e9zA/IGGL/vXu56d+zNVfg8La6TsU4O3loGrFIDOKgVEJm/x25Z1cg49nsONXx6SFC+DOsiL95k62e4dLDbHLhK/oE+3LpkZGPjPxdMTJm4wrZE0SuxmyhyVSPwlp10DPqlzO0zDerW5WheqCa6SZ6tNIjS9RHRi7q7IbJuL8DIn9GugwuTasqDCcrMYpSxNlSi7hzEsfoeqM2yUcsLytMpu+84bl5mGE4vuxI0Utty53wESAraMxm7H5FhVS6EFoQffrTIGwtqx/kFu8We7XOqvkIVn4vRPTnnPN6FmnGcTfgK/9eockhvnKp9VDqaZYtLdm0ciSMiI4nF8MjCfm2Z3uXdPbomPLZSH+E4i0wMYqx/ii1t8CEqk30x6u9ByZebWKwfgZxdihpzA5GzhixAzSbGGz5Fk3bs4OR25rWJtp4rtMI++a1c1r3rpF2Nm9yr3uek+mr3PGMj4ff7y1yr3O3s6y1FlLpSH8EM/s1cczxt+SaIns1MYqxI2MdGeu7YKxW4tZcUu5eJnCNRM3Nk6bnO8utLCpbYlvoqCca6AzK20gFYUZz3h9syijaWy2YE06XIFXWS8DMfHzWaEP/d1rCjpQB69sXfvOOCNVufbbnMbCeMpsG/IkI/5GIn0Ky/tlEGt5kXVB1iHJeXzJ1oHK+C6uPYdvK+8JbrcJz/+q9B/Q+xfqhNO+oxV+k+cBm6P/j4pktwU6vpf26YQfebjYeCrmLJvbFrLcSX8IYR845cs6rcE6z3dduJvVs5+3u5mXJFIbJIkJjMlUHNvu29/q6wPdrA7azRtcx/2rBnYGkqwpC/w0DB1+nYxVosQar5Kg4W7TJ1KhY0jj6OSiCh08uhKJL4iuc9jHC0t7vV8ISXHIZLjD2+G2i4kRdSAnhgtV+D+Q6u/dPe511nd3bOK3ZD2ECqkl1/N7yTwllQan3VTv0t0HoUMyfIdTKU/o5Wm1KpJuI9wTK3TeDGLh+xO4hjBmCyVvuEc3Lw3XDW5k9QUXyvx3k+YOou92dUbISJJQ5RiWPXzGGg3D94R//ff7NvCMAAA=="; }
        }
    }
}
