// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Colum_Audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Colum_Audit));
        
        string IMigrationMetadata.Id
        {
            get { return "201609231500034_Update_Colum_Audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1azW7jNhC+F+g7CDq1QNayk0sbyLvI2klhdJ0Eq2TvtDR2iKUolaQC+9l66CP1FTrU/58dyXay3YURwJFIzjc/5Axnxv7373/sD2ufGc8gJA342BwNhqYB3A08yldjM1LLd7+ZH97//JN97flr40u27kKvQ0oux+aTUuGlZUn3CXwiBz51RSCDpRq4gW8RL7DOh8PfrdHIAoQwEcsw7M8RV9SH+AVfJwF3IVQRYfPAAybTcZxxYlTjlvggQ+LC2HRmk7vBjC8FkUpErooEDKZEkcGcUD6Y05UgCmWUpnHFKEH5HGBL0yCcByqeuXyU4CgR8JUT4gBhD5sQcN2SMAmpVpfF8q4KDs+1glZBmEG5kVSB3xNwdJFazKqT72V3M7co2vQaba82WuvYrmPzQRAPMcRX06hzu5wwoVemdp/inLay/sipZPF4ZtSXneWHBs+W/jszJhHTuzbmEClB2JlxHy0Ydf+EzUPwFfiYR4yVBUaRca4ygEP3IghBqM1nWKZqzDzTsKp0Vp0wJyvRJPrNuLo4N41bZE4WDPLzULKFowIBfwAHPGLg3ROlQHCNAbFFG9xrvPRnxg0PIHqYaczJ+hPwlXoam/hoGjd0DV42kkrwyCk6JBLheYeXmEwExMKiS+TM9PMD1cwb2nUAC8QsvPI8AVLukP582En4/QRAjxVvztvBXY9ylT8GAQPCe6M8hh5av303ulAe0/id+B3H1mVWtlVEnJ1xaBKwQPSKQTGFTP6dYs8uR8K92bGro+GruNAnWBF38214vxBtX4nrlavoMxwaNE5B/BTEv6sgjgm8woALIhVjutDxV4/CWrVEdJQvDeoyZVbVKkF1QNUzVDRgIUeS2w9K6au1Gya5Llog0punTeFctaIosZKqJKterC3liz0nYYimL5Uz6YjhJLXM5J3TP533EwzLlS1ZfS5tzgk9j6ygNptcCDdUSKVrpwXRuz/x/May6kZusW7Gq7FX9XuzsHtGop9TT+1Y15W2uwZf2PcGVfbxYoy1h1zOcqXToI2LTcKIaLml8XhEPt920++iTm6hMn0y0h2heheUkaozPRErF0IDtTLbGzmJPi2gyUR3vCx6l6Gyse4o5ehdRiqP90XbZr3mbG/kpvUqE00826od+7rbWQ2/q2WqdU/u5OdpMH0VH0/icX//3kL3Or6d5LWVYx6PdEco58dlnPL4W8aaLHstY2Rjp4jVBe8Usb55xGokbvUlOfc8gaslanaaNL3cjG5kUckS00BDPVNPZ1DORirwkzDn/MUmjKK+xYI54XQJUiXtB8zMR+e1zvX/p4tsSemxrq3kN2+iUG3WF9skB3QR+DMR7hMRv/hk/WsZad++rPYRdcySPpOwUewdXrEfC7pakC+oOkIx3mbHHsXyPmbcsxbfC7ln//THcLxy07DVanED7+B+5NGg2wLFwaDVbuI+znIKO6ew8yphp97xa/aTOnb0djf0knwKbb0IUJlE1J79vu3tvjbwwzqBzcTRtsq/dbCnIOmqgNC/fODgag8tQLM1WCgH2d6iTmWJsiW1rZ+DIrj55EoouiSuwmkXD1jc/v1CWIRLrv0FeDN+F6kwUldSgr9glW+PbGs3/7jdWZXZvgvjsv0YKqCYVJ/fO/4xoszL5b5p+ug2CH0U05sIpXKUvpFWmxzpNuAdgVLzTSEEru+xB/BDhmDyjjtEx+X+sqFXJpdQlv9vB3l5I6pmt6eUrATxZYpR0OMrnmHPX7//D06xkgnyIwAA"; }
        }
    }
}
