// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Columns_Audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Columns_Audit));
        
        string IMigrationMetadata.Id
        {
            get { return "201609231600305_Update_Columns_Audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Y227bOBB9X6D/IOipC6SmnbzsBnKL1E4WxtZxUDl9p6WxQ5QitSQV2N+2D/tJ+ws71P1iO7JrFIsAgUxyzswckmdG+vfvf7xP24g7r6A0k2LsjgZD1wERyJCJzdhNzPrDb+6nj+9+8e7DaOt8K9bd2HVoKfTYfTEmviVEBy8QUT2IWKCklmszCGREaCjJ9XD4OxmNCCCEi1iO431NhGERpD/w50SKAGKTUD6XIXCdj+OMn6I6jzQCHdMAxq4/mywGM7FWVBuVBCZRMJhSQwdzysRgzjaKGoxRu84dZxTj84GvXYcKIU06c/uswTdKio0f4wDly10MuG5NuYY8q9tqed8Eh9c2QVIZFlBBoo2MTgQc3eSMkbb5Wby7JaPI6T1yb3Y265TXsbtUNEQM9d112t5uJ1zZlTnvU5yzLNt/pZWuHq+c9rKr8tDg2bJ/V84k4XbXxgISoyi/cp6SFWfBn7Bbyu8gxiLhvB4whoxzjQEcelIyBmV2X2GdpzELXYc07UjbsDSr2WT5zYS5uXadR3ROVxzK81DjwjdSwR8gAI8YhE/UGFDCYkDKaMd7y5f9X3jDA4g3zHXmdPsFxMa8jF18dJ0HtoWwGMkjeBYMLyQa4XmHt5xMFKTB4pUondnnJbPOO9n1AJNqFt+FoQKtj0R/PewV/HkB4I1VP923j7uelCl/lpIDFSejPMchsr9/N/pYXpL8Xv4uw3XdlUcqxenqEGq/QZ0AlYcxXVnZsKOwNXsECePLNUnnzppZZag+mLa4IYFVHFlZGNSUb1/EZWxVQSJZRSoqFzlQurw5jWPkrlbK8hHHz+rY5IN/upRHGQYJ9B5FL6MtPeHVoRtozaJrjPSBKW1s3VxRu32TMOosa+7EAZYLXx2y23pdcV+Y2Of8qvWs6bX9asFX/D5gyhEKcpo9lHHWq1zHNm00KKdqT3WYSJ5E4lCFOWad6X3dPhvpj9AU8zpSc+ZExIaid1AbsycjZ/KxBzSb6I9XyG8dqhjrj1KX3zpSffxUtEPsdWdPRu6y15jo4nmkdezb14507l2rQ2rf5GMy2F5Sei/lsCV7Xi5Bb7f1HU3KlrgOEvXKQqtH/k4biDJh8P/iE84w32rBnAq2Bm2yJhIL1ei69Q7w/+nHidYh79uU//RWmFla32x2T2yE6t2veKUqeKHqfUS3v9aRzu1w7R0xl+xwiwg7vc+PN7CXgm72pytmLtCb7uPxhN7xHBrPbE3PQj6tE+22ST07zeONZiZsyPVKYjJZqD/eh3aF1iP1ryzeFDTbVBD2m4uAwF6kCrRYg62YLLYA86tHVCxp7dAcDMU9onfKsDUNDE4HeA7St4dvlCe45D5aQTgTi8TEibnTGqIVb7wze+S4/7TZbsbsLeK0MbxEChgms8dsIT4njIdl3A/dq3QIwp6YXDIxKnx7QrjNrkR6lKInUE7fFGIQVnCXEMUcwfRC+PQVzokNL88X2NBgV9TLwyBvb0STdm/KKLbokc4xKnv75ZDYT4cf/wM4VH3DbBQAAA=="; }
        }
    }
}
