// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_DataType_Column_ShortName_Trademark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_DataType_Column_ShortName_Trademark));
        
        string IMigrationMetadata.Id
        {
            get { return "201610032136519_Update_DataType_Column_ShortName_Trademark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1a227jNhB9L9B/EPSctewELdpA3oXXTgqj6zhYJftOS2NHWIpSSSqNv20f+kn9hQ51M3WxLPlSLIoiQGCTnDPDmeFweJK/v/1lf3gLqPEKXPghG5ujwdA0gLmh57PN2Izl+t0v5of3P/5g33nBm/ElX3ej1qEkE2PzRcro1rKE+wIBEYPAd3kowrUcuGFgES+0rofDX63RyAKEMBHLMOzPMZN+AMkX/DoNmQuRjAldhB5QkY3jjJOgGg8kABERF8amM58uB3O25kRIHrsy5jCYEUkGC+KzwcLfcCLRRmEaE+oTtM8BujYNwlgok5nbZwGO5CHbOBEOEPq0jQDXrQkVkO3qdre86waH12qD1k4wh3JjIcOgJ+DoJvOYVRU/yu9m4VH06R36Xm7VrhO/js0nTjzE4F9No6rtdkq5Wpn5fYZzysvqVyEldh+vjOqyqyJpMLfUz5UxjamK2phBLDmhV8ZjvKK++ztsn8KvwMYsplQ3GE3GudIADj3yMAIut59hnW1j7pmGVZazqoKFmCaT7m/O5M21aTygcrKiUOSD5gtHhhx+AwaYYuA9EimBM4UBiUdr2iu6ppjbuTZMQDxhprEgb5+AbeTL2PzZNO79N/Dy75n+Z+bjcUQRzHY4yr5pGEQxDhyy7xNsiLs9YOX1cVa2a1a/W3T+NLyEUucl5PI8mtsVLf/EiLQoGQ3PoWXiSv+12MvHMKRAWG+nTDkkuYQVtcBSn5/8oL+HE7CQz6OJ53EQoi2tLhLizAAs+G3+v4xuBw9lLE6Nx3Pkofebo9FF8pzO76TvPL7WVdnW7sJqvcYmr8RPfKsXsh4XWoO8aBr8/5I7/pIbXeSszT2l8NAm2zF0hAsVifZMxiZYYi4BzwyarVRqqVF4kw2JjCcty2WRaS/vL0V1QFa7PCwFOzvS/nigtYBWO0zTKWkAbDyMTc4otr1r+q20689fB9ae54G9IFGEcdKeC9mI4aRvhek7p3+7HKQYlisauubC2kITHheygcpseg7ufS6kepusiEqFqRfUlpWDvMfzua5aHKvlYheFXER9zu6jju8mLRUq8Dv/3uOWA6wHye6hsFN/SdRkk8ccoYQ3FKdpSOOA7StwbdJpXuny9UxrR9DzU8fZl7ftaGk/qeOkI90RtLZUh9GGu2NlnaeOkw11x8j7Sh0kH+sRp1JfWYpXaaYnYqm5rKGWZnsjp51MA2g60SOiWSdYCmc21h1F7wR1JH28L9o+79VneyPXvVeaqOPZVqW4VIubVatulTaoWi87VdPG6+widbXpRuxfYTuhfK+1Nu/TyjakY91R6hj7EC6aU7UGprqk0F40MpWGxc6ah8OkZ62bSJeYBrrm1fdUJ+FshYQgTT3nDzqlPu53t2BBmL8GIdPXB7azo+sKQ/r9sJWWEB7tSln+628oX7n14CupL1OhPZvYK+HuC+FVdvAgvddTZ53va1Lc/yWlc2pNiIpUO5WrO4zbm5lrgkyouX6YZR5u5cuzcHDq6pTn5OAak+y6f2QaKLZzQZcZtGM8WWfPmvzYg906xo1HkmdHIZ/Elf33KmnzkT6RXkqsPoFcOup09KOO6uRDR2qonRlKmw48RKsQN5PaehJx1JU3alJ8ToKp3ofZlv4nansGwt/sINQfrBm4qkjvQPM1+BYI8/Dj7nWL8iWV7FiAJHj+yYRLf01cidMu1piEgvxCaIxL7oIVeHO2jCXe9RMhIFjREhdrW+36ExatbLO9jJKXyTm2gGb6qoQt2cfYp15h931DKu+BUBHM6gBa5UhVDzbbAukhZB2BMvfNIAKmqsgTBBFFMLFkDlFXc3/bsDCnaZa30/tBDgei7HZ75hN8IwYiw9jJq3+7sNT/Xbz/B6g55MypIQAA"; }
        }
    }
}
