// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Columns_Color : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Columns_Color));
        
        string IMigrationMetadata.Id
        {
            get { return "201609231510032_Update_Columns_Color"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1a227jNhB9L9B/EPTUAlkrFyDoBvIusnZSGF0nwSrZd1oaO8RSlEpSgf1t+9BP6i90qPvNtuTY2bYwAjgSyTlzIWc4M/bf3/+yPy59ZryAkDTgQ/NscGoawN3Ao3wxNCM1f/eb+fHDzz/ZN56/NL5m6y70OqTkcmg+KxVeWZZ0n8EncuBTVwQymKuBG/gW8QLr/PT0vXV2ZgFCmIhlGPaXiCvqQ/yCr6OAuxCqiLBp4AGT6TjOODGqcUd8kCFxYWg6k9H9YMLngkglIldFAgZjoshgSigfTOlCEIUyStO4ZpSgfA6wuWkQzgMVz1w9SXCUCPjCCXGAsMdVCLhuTpiEVKurYnlXBU/PtYJWQZhBuZFUgd8T8OwitZhVJ9/J7mZuUbTpDdperbTWsV2H5qMgHmKIb6ZR53Y1YkKvTO0+xjltZf2RU8ni8cSoLzvJDw2eLf13YowipndtyCFSgrAT4yGaMer+AavH4BvwIY8YKwuMIuNcZQCHHkQQglCrLzBP1Zh4pmFV6aw6YU5Wokn0m3B1cW4ad8iczBjk56FkC0cFAn4HDnjEwHsgSoHgGgNiiza413jpz4wbHkD0MNOYkuVn4Av1PDTx0TRu6RK8bCSV4IlTdEgkwvMO25iMBMTCokvkzPTzI9XMG9p1AAvEJLz2PAFSbpD+/LST8LsJgB4r3py3g7se5Sp/CgIGhPdGeQo9tH77bnSh3KfxO/Hbj63LrGyriDgb49AoYIHoFYNiCpn8O8aeTY6Ee7NhVy8P4UCfYUHc1RbOF4fgvCXSXh4kXly7ir7Aa+PFMX4f4/d/Kn5j7q4w1oJIxRjPdOjVo7BULcEc5UvjuUyZVbVKUB1Q9eQUDVjIkaT1g1Lmam2GSW6KFoj00mlTOFetqEespCDJChdrTeViT0kYoulLlUw6YjhJGTN65/TP5P0Ew3JlS0KfS5tzQs8jC6jNJnfBLRVS6bJpRvTujzy/say6kWusm/Fq7FX9yizsnpHo59RTO5Z0pe2uwRf2vUWVfbwTY+0hl7Nc5DRo4zqTMCJaLmg8HpHP113ym6iTS6hMn4x0R6jeBWWk6kxPxMqF0ECtzPZGTqJPC2gy0R0vi95lqGysO0o5epeRyuN90dZZrznbG7lpvcpEE8+2ase+7nZWw+9qSWrdkzv5eRpMD+LjSTzu799r6A7j20lSWznm8Uh3hHJyXMYpj79lrMmy1zJGNnaMWF3wjhHrh0esRuJWX5JzzxO4WqJmp0nT9j50I4tKlpgGGuqFejqDclZSgZ+EOedPNmIU9S0WTAmnc5Aq6TxgZn52Xmta/3sayJaUHuvaRX7z/gnVZt3aIXlFE4G/EOE+E/GLT5a/lpF2bclqH1H7LOkzCRvF3usr9n1BVwvyGVV7KMbb7NijWN7FjDvW4jsh92yd/j8cr9wxbLXa5R5aka3AF3sJEo1e46saibv4yTHiHCPOQSJOvdnXbCV1bOZt7uUlqRTaehagMomoPVt96zt9beCvawI2c0bbKv/CwR6DpIsCQv/egYOrPbQAzdZgjRxke4s6lSXKltS2fgqK4OaTa6HonLgKp108YHHn9ythES658WfgTfh9pMJIXUsJ/oxVvjOyrc38405nVWb7Powr9n2ogGJSfX7v+aeIMi+X+7bpo+sg9FFMLyGUylH6MlqscqS7gHcESs03hhC4vsIewQ8Zgsl77hAdl/vLhl6Z3EBZ6r8eZPtGVM1ujylZCOLLFKOgx1c8w56//PAPrmFYGOgjAAA="; }
        }
    }
}
