// <auto-generated />
namespace SICO.Infrastructure.Data.Main.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_Columns_Trademark2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Columns_Trademark2));
        
        string IMigrationMetadata.Id
        {
            get { return "201609232124268_Update_Columns_Trademark2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Z227jNhB9L9B/EPSctWwHLdpA3kXWTgqj6zhYJftOS2ObWIpSSSqNv60P/aT+Qoe6Uhc7UuIUhQHDJjlnhjMUzxz7n7/+dj89h8x6AiFpxGf2ZDS2LeB+FFC+m9mJ2n74xf708ccf3JsgfLa+Fesu9Tq05HJm75WKrxxH+nsIiRyF1BeRjLZq5EehQ4LImY7HvzqTiQMIYSOWZblfE65oCOkX/DqPuA+xSghbRQEwmY/jjJeiWnckBBkTH2a2t5yvR0u+FUQqkfgqETBaEEVGK0L5aEV3giiMUdrWNaME4/OAbW2LcB6pdObqUYKnRMR3XowDhD0cYsB1W8Ik5Lu6qpb33eB4qjfoVIYFlJ9IFYUDASeXecacpvmr8m6XGcWc3mDu1UHvOs3rzH4QJEAM8d22mt6u5kzolXneFzins6zfSitZfbywmssuykODZ0u/Lqx5wnTVZhwSJQi7sO6TDaP+73B4iL4Dn/GEMTNgDBnnagM4dC+iGIQ6fIVtvo1lYFtO3c5pGpZmhk22vyVXl1PbukPnZMOgPA9GLjwVCfgNOOARg+CeKAWCawxIM9ry3vA1x7NdeMMDiE+Yba3I8xfgO7Wf2T/b1i19hqD4nvt/5BQfRzTB0w4d8Z32+QV2xD+84Hn6Hp71+wmfP43fw6m3j4Q6j+fTjtZ/4ik44WQyPoeXa1/Rp3Ivn6OIAeGDkzIXkJ5fvCVLLP35gYbDM5yCRWIZXweBAClPHat3KXEeAF7ip/L/Pr49vAgS+dZ6PMYBZr+7Gn0sz5n8Xv7Ok2vTletUJNSmJmwHFFIHiDyMxUYziR6FZ9XBURhfTlMyd1bfVYbqgWryHSawiiPrFEYGGXZFXMZW9ShO1qQUzYxzpJtxVySOMXdGd5OPWF7W2sw/eMPZPcwwHF92kHwZbekJHx2yg8Zsxk23VEilW6kN0eWbB2FrWb0SR7Jc+Golu0nhVe4LE/05f9R6tnlGvRrwVX5vccshcnS6eyjjNBuflm3aexJGREfDMI9YEvJjTccp64yITftspD+CSegmjjneHy2jShMnG+mPYDCuCWMM98fKSdXEyYf6YxSUaYIUYwPqVKPMWr1qMwMRa7zZQq3NDkbOLukO0GxiQEVzkquVMx/rj2KSnIlkjg9FO5a99uxg5Hb2ahNtPNdpXC7Ny81p3W4NadK8L0+RTXNJ6b0knQa5uPlF/7Kebt382RLbwkQ90UDf+t5BKgiz69f7g80Zxf1WC1aE0y1Ilak3bAcm04b4/v8IYUfKgPVVw/+5BqU6rS+qzKENsyH++BMR/p6IpvB8s6rsBO6S0/1FYyekFm9v1YQ9gAdLwE7MVAQOA60rvg1VZ1F7+iZT51R73eUeXpsOMXcu6LpWe00m2zqtK48DdNRr0vhKmfYq5GGqrC0Zeqqu06Irox/M9SbCzWShvl2TtenQdcwfod0FSLqrIPRP0hx8/SBVoMUalCVRUQLcnxlRsaRRoRUogjUi10LRLfEVTvt4DlIl/Y2wBJfchBsIlnydqDhR11JCuGG1nxRd57T/VHjWY3bXcSqSzrEFDJPqY7bmnxPKgjLu2/ajdAxCn5ic2DAqT2mC2x1KpLuI9wTK07eAGLimxQcIY4Zgcs09oq/P4bHhw5OxWtHVHAd5uRD1tLsLSlCuhjLHqOz1HyuO/mfl47/CE/lfixkAAA=="; }
        }
    }
}
